"""Editor environment implementation - Query-based pipeline system.

Provides a procedural query-based view system where views are generated by
re-executing queries on every screen refresh, ensuring views always show
current content even as files change.
"""

import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from orchestrator.core_types import CommandResponse
from orchestrator.declarative import DeclarativeEnvironment, command
from orchestrator.environments.editor.executor import QueryExecutor
from orchestrator.environments.editor.parser import ParseError, QueryParser
from orchestrator.environments.editor.summarizer import Summarizer
from orchestrator.environments.editor.windows import Window, WindowManager

# Limits
PEEK_HARD_LIMIT = 300  # Max lines for peek command
MAX_TOTAL_LINES = 3000  # Max total lines across all active views
MAX_QUERIES = 50  # Max active queries


@dataclass
class Query:
    """A stored query for persistent views."""

    label: str
    query_string: str  # Original query string for re-execution
    ast: object  # QueryAST from parser
    glob_pattern: str  # May be modified by exclusions
    original_glob: str
    excluded_files: set[Path]
    created_at: float


class EditorEnvironment(DeclarativeEnvironment):
    """Editor environment with query-based pipeline views.

    All views are procedural - they re-execute queries on every screen refresh.
    This ensures views always show current content even as files change.
    """

    def __init__(self, project_dir: Path) -> None:
        """Initialize editor environment.

        Args:
            project_dir: Root directory for file operations
        """
        super().__init__()
        self._project_dir = project_dir

        # New components
        self._parser = QueryParser()
        self._executor = QueryExecutor(project_dir)
        self._window_manager = WindowManager()
        self._summarizer = Summarizer()

        # Active queries (label → Query)
        self._active_queries: dict[str, Query] = {}

        # Tag-level summary tracking
        self._tag_windows: list[Window] = []
        self._tag_patterns: list[str] = []

        # Cached windows for edit verification
        self._cached_windows: list[Window] = []

    @command(
        signature="view <label> <matcher> in <glob> | <operations>",
        description="Create persistent query-based view.\n\nMatchers:\n  /pattern/ in <glob> - Search for pattern\n\nOperations:\n  context N - Expand N lines up/down\n  while-indent - Expand while indented\n  until /pattern/ - Expand until pattern\n  filter /pattern/ - Keep only matching windows\n  limit N - Keep first N windows\n\nExamples: context 5, while-indent, until /^class/, filter /TODO/, limit 10",
        example="view secrets /sops\\.secrets/ in **/*.nix | context 3",
    )
    def _handle_view(self, cmd: str) -> CommandResponse:
        """Handle view command."""
        try:
            # Parse query
            ast = self._parser.parse_view(cmd)
        except ParseError as e:
            return CommandResponse(output=str(e), processed=False)

        # Execute pipeline
        try:
            windows = self._executor.execute(ast, excluded_files=set())
        except Exception as e:
            return CommandResponse(
                output=f"Query execution failed: {e}", processed=False
            )

        # Check total size limit
        total_lines = sum(w.line_count for w in windows)
        existing_lines = self._calculate_existing_lines()

        if total_lines + existing_lines > MAX_TOTAL_LINES:
            return CommandResponse(
                output=f"Would exceed total limit ({total_lines + existing_lines}/{MAX_TOTAL_LINES} lines). Close views first or refine query.",
                processed=False,
            )

        # Check query count limit
        if (
            ast.label not in self._active_queries
            and len(self._active_queries) >= MAX_QUERIES
        ):
            return CommandResponse(
                output=f"Would exceed query limit ({MAX_QUERIES}). Close some queries first.",
                processed=False,
            )

        # Store query (override if label exists)
        if windows:  # Only store if has matches
            from orchestrator.environments.editor.parser import PatternMatcher

            self._active_queries[ast.label] = Query(
                label=ast.label,
                query_string=cmd,
                ast=ast,
                glob_pattern=(
                    ast.matcher.glob if isinstance(ast.matcher, PatternMatcher) else ""
                ),
                original_glob=(
                    ast.matcher.glob if isinstance(ast.matcher, PatternMatcher) else ""
                ),
                excluded_files=set(),
                created_at=time.time(),
            )

        # Add to tag tracking for summary
        self._tag_windows.extend(windows)
        from orchestrator.environments.editor.parser import PatternMatcher

        if isinstance(ast.matcher, PatternMatcher):
            self._tag_patterns.append(ast.matcher.pattern)

        # Format response
        return CommandResponse(
            output=self._format_view_response(windows, ast.label, total_lines),
            processed=True,
        )

    @command(
        signature="peek <matcher> in <glob> | <operations>",
        description="Transient read (300 line limit, not stored).\n\nMatchers:\n  /pattern/ in <glob> - Search for pattern\n  line N in <file> - Specific line\n  line N-M in <file> - Line range\n\nOperations: Same as view",
        example="peek line 155 in file.c | context 10",
    )
    def _handle_peek(self, cmd: str) -> CommandResponse:
        """Handle peek command."""
        try:
            # Parse query
            ast = self._parser.parse_peek(cmd)
        except ParseError as e:
            return CommandResponse(output=str(e), processed=False)

        # Execute pipeline
        try:
            windows = self._executor.execute(ast, excluded_files=set())
        except Exception as e:
            return CommandResponse(
                output=f"Query execution failed: {e}", processed=False
            )

        # Check peek limit
        total_lines = sum(w.line_count for w in windows)
        if total_lines > PEEK_HARD_LIMIT:
            return CommandResponse(
                output=f"Query matched {total_lines} lines - exceeds peek limit ({PEEK_HARD_LIMIT}). Refine query.",
                processed=False,
            )

        # Add to tag tracking for summary (but don't store)
        self._tag_windows.extend(windows)
        from orchestrator.environments.editor.parser import PatternMatcher

        if isinstance(ast.matcher, PatternMatcher):
            self._tag_patterns.append(ast.matcher.pattern)

        # Format and return window contents
        return CommandResponse(
            output=self._format_peek_response(windows), processed=True
        )

    @command(
        signature="edit <file> <start>-<end>",
        description="Edit visible lines.\n\nLines must be visible in a view.\nContent verification ensures file hasn't changed.",
        example="edit src/main.py 45-52\nnew content here",
    )
    def _handle_edit(self, cmd_lines: list[str]) -> CommandResponse:
        """Handle edit command."""
        if not cmd_lines:
            return CommandResponse(output="No edit command provided", processed=False)

        # Parse edit (multi-line)
        parsed = self._parse_edit(cmd_lines)
        if not parsed:
            return CommandResponse(
                output="Invalid edit syntax. Expected: edit <file> <start>-<end>",
                processed=False,
            )

        filepath = self._project_dir / parsed["filepath"]
        start_line = parsed["start_line"]
        end_line = parsed["end_line"]
        new_content = parsed["new_content"]

        # Find containing window
        containing_window = None
        for window in self._cached_windows:
            if (
                window.filepath == filepath
                and window.start_line <= start_line
                and window.end_line >= end_line
            ):
                containing_window = window
                break

        if not containing_window:
            return CommandResponse(
                output="Can only edit lines visible in a view", processed=False
            )

        # Verify content matches
        current_lines = self._read_file_lines(filepath)
        if not current_lines:
            return CommandResponse(
                output=f"Cannot read file: {filepath}", processed=False
            )

        window_slice = current_lines[
            containing_window.start_line - 1 : containing_window.end_line
        ]

        if window_slice != containing_window.lines:
            return CommandResponse(
                output="File changed since view was generated. Refresh views.",
                processed=False,
            )

        # Perform edit
        new_lines = (
            current_lines[: start_line - 1] + new_content + current_lines[end_line:]
        )
        try:
            filepath.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
        except (OSError, IOError) as e:
            return CommandResponse(output=f"Write failed: {e}", processed=False)

        return CommandResponse(
            output=f"Edited {filepath.relative_to(self._project_dir)} lines {start_line}-{end_line}",
            processed=True,
        )

    @command(
        signature="close pattern <glob>",
        description="Remove all queries matching label pattern\nExample:\n<editor>\nclose pattern hypothesis_1_*\n</editor>",
        example='close pattern "hypothesis_1_*"',
    )
    def _handle_close(self, cmd: str) -> CommandResponse:
        """Handle all close command variants.

        Supports:
        - close label <name>
        - close pattern <glob>
        - close all
        """
        import fnmatch

        cmd = cmd.strip()

        # Parse close command variants
        if cmd == "close all":
            count = len(self._active_queries)
            self._active_queries.clear()
            return CommandResponse(output=f"Closed all {count} queries", processed=True)
        elif cmd.startswith("close label "):
            label = cmd[12:].strip()
            if label in self._active_queries:
                del self._active_queries[label]
                return CommandResponse(output=f"Closed query '{label}'", processed=True)
            return CommandResponse(output=f"No query '{label}'", processed=False)
        elif cmd.startswith("close pattern "):
            pattern = cmd[14:].strip()
            # Strip quotes if present
            if (pattern.startswith('"') and pattern.endswith('"')) or (
                pattern.startswith("'") and pattern.endswith("'")
            ):
                pattern = pattern[1:-1]

            to_remove = [
                label
                for label in self._active_queries.keys()
                if fnmatch.fnmatch(label, pattern)
            ]

            if not to_remove:
                return CommandResponse(
                    output=f"No queries match pattern '{pattern}'", processed=False
                )

            for label in to_remove:
                del self._active_queries[label]

            return CommandResponse(
                output=f"Closed {len(to_remove)} queries matching '{pattern}'",
                processed=True,
            )
        else:
            return CommandResponse(
                output="Invalid close syntax. Use: close label <name>, close pattern <glob>, or close all",
                processed=False,
            )

    @command(
        signature="create <file>",
        description="Create new file with content",
        example="create src/new.py\nprint('hello')\n",
    )
    def _handle_create(self, cmd_lines: list[str]) -> CommandResponse:
        """Handle create command."""
        if not cmd_lines:
            return CommandResponse(output="No create command provided", processed=False)

        # Parse: first line is "create <filepath>", rest is content
        first_line = cmd_lines[0].strip()
        if not first_line.startswith("create "):
            return CommandResponse(
                output="Invalid create syntax. Expected: create <file>", processed=False
            )

        filepath_str = first_line[7:].strip()  # Remove "create "
        filepath = self._project_dir / filepath_str

        # Validate filepath
        is_valid, error_msg = self._validate_filepath(filepath_str)
        if not is_valid:
            return CommandResponse(output=error_msg, processed=False)

        # Check if file exists
        if filepath.exists():
            return CommandResponse(
                output=f"File already exists: {filepath_str}", processed=False
            )

        # Get content (everything after first line)
        new_content = cmd_lines[1:] if len(cmd_lines) > 1 else []

        # Create parent directory if needed
        filepath.parent.mkdir(parents=True, exist_ok=True)

        # Write file
        try:
            filepath.write_text("\n".join(new_content) + "\n", encoding="utf-8")
        except (OSError, IOError) as e:
            return CommandResponse(output=f"Create failed: {e}", processed=False)

        return CommandResponse(
            output=f"Created {filepath_str} ({len(new_content)} lines)", processed=True
        )

    def get_state_display(self) -> str:
        """Generate screen by re-executing all queries."""
        all_windows = []
        queries_to_remove = []

        # Re-execute all active queries
        for label, query in self._active_queries.items():
            try:
                windows = self._executor.execute(query.ast, query.excluded_files)

                if not windows:
                    queries_to_remove.append(label)
                else:
                    all_windows.extend(windows)
            except Exception:
                # Query execution failed - remove it
                queries_to_remove.append(label)

        # Auto-remove exhausted/failed queries
        for label in queries_to_remove:
            del self._active_queries[label]

        # Cache for edit verification
        self._cached_windows = all_windows

        # Merge and deduplicate
        views = self._window_manager.merge_overlapping(all_windows)

        # Format for screen
        return self._window_manager.format_for_screen(
            views, total_queries=len(self._active_queries)
        )

    def generate_tag_summary(self) -> str:
        """Called on </editor> tag close to generate AI summary."""
        if not self._tag_windows:
            return ""

        summary, metadata = self._summarizer.generate_summary(
            self._tag_windows, self._tag_patterns
        )

        # Clear tag state
        self._tag_windows = []
        self._tag_patterns = []

        return f"\nSummary: {summary}"

    def _execute_command(self, method, cmd_text: str) -> str:
        """Override to handle multi-line commands."""
        cmd_lines = cmd_text.split("\n")
        first_line = cmd_lines[0].strip()

        # Multi-line commands (edit and create)
        if first_line.startswith("edit ") or first_line.startswith("create "):
            response = method(cmd_lines)
        else:
            # Single-line commands: pass first line
            response = method(first_line)

        # Convert CommandResponse to string
        if isinstance(response, CommandResponse):
            if not response.processed:
                raise ValueError(response.output)
            return response.output

        return response

    # Helper methods
    def _calculate_existing_lines(self) -> int:
        """Calculate total lines from existing queries."""
        total = 0
        for query in self._active_queries.values():
            try:
                windows = self._executor.execute(query.ast, query.excluded_files)
                total += sum(w.line_count for w in windows)
            except Exception:
                pass
        return total

    def _format_view_response(
        self, windows: list[Window], label: str, total_lines: int
    ) -> str:
        """Format view command response."""
        if not windows:
            return f"Query '{label}' matched no results"

        files = len(set(w.filepath for w in windows))
        existing = len(self._active_queries)

        return (
            f"Created query '{label}' with {len(windows)} windows across {files} file(s)\n"
            f"Total: {total_lines} lines ({existing} queries active, {self._calculate_existing_lines()}/{MAX_TOTAL_LINES} lines used)"
        )

    def _format_peek_response(self, windows: list[Window]) -> str:
        """Format peek command response."""
        if not windows:
            return "No matches found"

        lines = []
        total_lines = sum(w.line_count for w in windows)
        lines.append(
            f"Found {len(windows)} windows ({total_lines}/{PEEK_HARD_LIMIT} lines):\n"
        )

        for w in windows[:10]:  # Show first 10
            lines.append(
                f"{w.filepath.relative_to(self._project_dir)} lines {w.start_line}-{w.end_line}:"
            )
            for i, line in enumerate(w.lines[:50]):  # Show first 50 lines per window
                line_num = w.start_line + i
                display_line = line[:200] if len(line) > 200 else line
                lines.append(f"  {line_num:4d}  {display_line}")
            if len(w.lines) > 50:
                lines.append(f"  ... ({len(w.lines) - 50} more lines)")
            lines.append("")

        if len(windows) > 10:
            lines.append(f"... and {len(windows) - 10} more windows")

        return "\n".join(lines)

    def _parse_edit(self, cmd_lines: list[str]) -> Optional[dict]:
        """Parse edit command."""
        if not cmd_lines:
            return None

        match = re.match(r"edit\s+(\S+)\s+(\d+)-(\d+)$", cmd_lines[0].strip())
        if not match:
            return None

        filepath_str = match.group(1)
        start_line = int(match.group(2))
        end_line = int(match.group(3))
        new_content = cmd_lines[1:] if len(cmd_lines) > 1 else []

        return {
            "filepath": filepath_str,
            "start_line": start_line,
            "end_line": end_line,
            "new_content": new_content,
        }

    def _validate_filepath(self, filepath_str: str) -> tuple[bool, str]:
        """Validate filepath is within project directory."""
        try:
            filepath = (self._project_dir / filepath_str).resolve()
            project_dir_resolved = self._project_dir.resolve()

            if not filepath.is_relative_to(project_dir_resolved):
                return (
                    False,
                    f"Path outside project directory: {filepath_str}",
                )
            return (True, "")
        except (ValueError, OSError) as e:
            return (False, f"Invalid path: {filepath_str} ({e})")

    def _read_file_lines(self, filepath: Path) -> list[str]:
        """Read all lines from file."""
        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                return [line.rstrip("\n") for line in f.readlines()]
        except (OSError, IOError):
            return []
