"""Editor environment implementation - Query-based pipeline system.

Provides a procedural query-based view system where views are generated by
re-executing queries on every screen refresh, ensuring views always show
current content even as files change.
"""

import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from orchestrator.core_types import CommandResponse
from orchestrator.declarative import DeclarativeEnvironment, command
from orchestrator.environments.editor.executor import QueryExecutor
from orchestrator.environments.editor.parser import ParseError, QueryParser
from orchestrator.environments.editor.summarizer import Summarizer
from orchestrator.environments.editor.windows import View, Window, WindowManager

# Limits
READ_ONLY_PEEK_HARD_LIMIT = 3000  # Max lines for read-only-peek command
MAX_TOTAL_LINES = 3000  # Max total lines across all active views
MAX_QUERIES = 50  # Max active queries


@dataclass
class Query:
    """A stored query for persistent views."""

    label: str
    query_string: str  # Original query string for re-execution
    ast: object  # QueryAST from parser
    glob_pattern: str  # May be modified by exclusions
    original_glob: str
    excluded_files: set[Path]
    created_at: float


class EditorEnvironment(DeclarativeEnvironment):
    """Editor environment with query-based pipeline views.

    All views are procedural - they re-execute queries on every screen refresh.
    This ensures views always show current content even as files change.
    """

    def __init__(self, project_dir: Path) -> None:
        """Initialize editor environment.

        Args:
            project_dir: Root directory for file operations
        """
        super().__init__(project_dir=project_dir)
        self._project_dir = project_dir

        # New components
        self._parser = QueryParser()
        self._executor = QueryExecutor(project_dir)
        self._window_manager = WindowManager()
        self._summarizer = Summarizer()

        # Active queries (label → Query)
        self._active_queries: dict[str, Query] = {}

        # Tag-level summary tracking
        self._tag_windows: list[Window] = []
        self._tag_patterns: list[str] = []

        # Cached windows for edit verification (stores merged views after get_state_display)
        self._cached_windows: list[Window | View] = []

    @command(
        signature="view <label> <matcher> in <glob> | <operations>",
        examples=[
            ("View all sections headings in a markdown file", "view /^# / in file.md"),
            (
                "View a section in a markdown file",
                "view /^# Introduction/ in file.md | until /^# /",
            ),
            (
                "View all mentions of John in any text file with 3 lines of context",
                "view /John/ in **/*.txt | context 3",
            ),
            (
                "Show all python functions using function `foobar`",
                "view /foobar\(.*\)/ in **/*.py | up-until /def.*\(.*\).*:/ | while-indent",
            ),
            (
                "Show all python functions using function `foobar` (alternative)",
                "view /def.*\(.*\).*:/ in **/*.py | while-indent | filter /foobar\(.*\)/",
            ),
        ],
    )
    def _handle_view(self, cmd: str) -> CommandResponse:
        """Create a persistent query whose results appear on every screen refresh.
        Use pattern-matching to select the text you want to show on screen.

        Parameters:
          label      — alphanumeric identifier; reusing a label overwrites the
                       existing view with the same name
          matcher    — pattern matcher (see Matchers reference below)
          glob       — file glob passed to the matcher (e.g. **/*.py)
          operations — optional pipeline of expand/filter steps (see Operations)

        The view is stored and re-executed on every screen refresh, so it always
        reflects the latest file content without any manual refresh step.

        Limits: up to 50 active queries; total lines across all views capped at
        3000 — the command is rejected if adding this view would exceed the cap.
        Close unused views to free the budget.
        """
        try:
            # Parse query
            ast = self._parser.parse_view(cmd)
        except ParseError as e:
            return CommandResponse(output=str(e), processed=False)

        # Execute pipeline
        try:
            windows = self._executor.execute(ast, excluded_files=set())
        except Exception as e:
            return CommandResponse(
                output=f"Query execution failed: {e}", processed=False
            )

        # Check total size limit
        total_lines = sum(w.line_count for w in windows)
        existing_lines = self._calculate_existing_lines()

        if total_lines + existing_lines > MAX_TOTAL_LINES:
            return CommandResponse(
                output=f"Would exceed total limit ({total_lines + existing_lines}/{MAX_TOTAL_LINES} lines). Close views first or refine query.",
                processed=False,
            )

        # Check query count limit
        if (
            ast.label not in self._active_queries
            and len(self._active_queries) >= MAX_QUERIES
        ):
            return CommandResponse(
                output=f"Would exceed query limit ({MAX_QUERIES}). Close some queries first.",
                processed=False,
            )

        # Store query (override if label exists)
        if windows:  # Only store if has matches
            from orchestrator.environments.editor.parser import PatternMatcher

            self._active_queries[ast.label] = Query(
                label=ast.label,
                query_string=cmd,
                ast=ast,
                glob_pattern=(
                    ast.matcher.glob if isinstance(ast.matcher, PatternMatcher) else ""
                ),
                original_glob=(
                    ast.matcher.glob if isinstance(ast.matcher, PatternMatcher) else ""
                ),
                excluded_files=set(),
                created_at=time.time(),
            )

        # Add to tag tracking for summary
        self._tag_windows.extend(windows)
        from orchestrator.environments.editor.parser import PatternMatcher

        if isinstance(ast.matcher, PatternMatcher):
            self._tag_patterns.append(ast.matcher.pattern)

        # Format response
        return CommandResponse(
            output=self._format_view_response(windows, ast.label, total_lines),
            processed=True,
        )

    @command(
        signature="read-only-peek <matcher> in <glob> | <operations>",
        examples=[
            (
                "Peek at a specific line with context",
                "read-only-peek line 155 in file.c | context 10",
            ),
            (
                "Search for pattern (transient)",
                "read-only-peek /TODO/ in **/*.py | limit 20",
            ),
        ],
    )
    def _handle_read_only_peek(self, cmd: str) -> CommandResponse:
        """Read file content read-only — results appear in the response only, not on screen.

        Snippets shows this way will not be updated if the file changes, and
        may be compacted when the coversation history becomes too large.

        They are also opened read-only. Only snippets opened with `view` may be edited.

        On the other hand, contents opened with read-only-peek are better cached
        by LLM providers, and therefore may be cheaper to process.

        Parameters:
          matcher    — pattern or line matcher (see Matchers reference below);
                       line matchers (line N, line N-M) are available in read-only-peek but
                       not in view
          glob / file — files to search, or exact file path for line matchers
          operations — optional pipeline of expand/filter steps (see Operations)

        Hard limit of 3000 lines per read-only-peek — the command is rejected if the result
        would exceed it. Refine the query with filter or limit operations.
        Results are not stored and do not appear on subsequent screens.
        """
        try:
            # Parse query
            ast = self._parser.parse_read_only_peek(cmd)
        except ParseError as e:
            return CommandResponse(output=str(e), processed=False)

        # Execute pipeline
        try:
            windows = self._executor.execute(ast, excluded_files=set())
        except Exception as e:
            return CommandResponse(
                output=f"Query execution failed: {e}", processed=False
            )

        # Check read-only-peek limit
        total_lines = sum(w.line_count for w in windows)
        if total_lines > READ_ONLY_PEEK_HARD_LIMIT:
            return CommandResponse(
                output=f"Query matched {total_lines} lines - exceeds read-only-peek limit ({READ_ONLY_PEEK_HARD_LIMIT}). Refine query.",
                processed=False,
            )

        # Add to tag tracking for summary (but don't store)
        self._tag_windows.extend(windows)
        from orchestrator.environments.editor.parser import PatternMatcher

        if isinstance(ast.matcher, PatternMatcher):
            self._tag_patterns.append(ast.matcher.pattern)

        # Format and return window contents
        return CommandResponse(
            output=self._format_read_only_peek_response(windows), processed=True
        )

    @command(
        signature="edit <file> <start>-<end>",
        examples=[
            (
                "Replace lines 45-52 in a file",
                "edit src/main.py 45-52\nnew content here\nmore lines",
            ),
        ],
    )
    def _handle_edit(self, cmd_lines: list[str]) -> CommandResponse:
        """Replace a range of lines in a file with new content.

        Parameters:
          file       — path relative to the project directory
          start-end  — 1-based inclusive line range to replace
          content    — replacement lines, written on the lines following the
                       edit command (multiline command)

        The target lines must be currently visible in an active view. This
        prevents editing stale content: if the file has changed since the view
        was last generated the edit is rejected — refresh the view first.

        The specified line range is replaced verbatim by the content lines.
        Providing zero content lines deletes the range.
        """
        if not cmd_lines:
            return CommandResponse(output="No edit command provided", processed=False)

        # Parse edit (multi-line)
        parsed = self._parse_edit(cmd_lines)
        if not parsed:
            return CommandResponse(
                output="Invalid edit syntax. Expected: edit <file> <start>-<end>",
                processed=False,
            )

        filepath = self._project_dir / parsed["filepath"]
        start_line = parsed["start_line"]
        end_line = parsed["end_line"]
        new_content = parsed["new_content"]

        # Find containing window
        containing_window = None
        for window in self._cached_windows:
            if (
                window.filepath == filepath
                and window.start_line <= start_line
                and window.end_line >= end_line
            ):
                containing_window = window
                break

        if not containing_window:
            return CommandResponse(
                output="Can only edit lines visible in a view. "
                "Open the relevant file section in a `view` first "
                "(NOT `read-only-peek`!)",
                processed=False,
            )

        # Verify content matches
        current_lines = self._read_file_lines(filepath)
        if not current_lines:
            return CommandResponse(
                output=f"Cannot read file: {filepath}", processed=False
            )

        window_slice = current_lines[
            containing_window.start_line - 1 : containing_window.end_line
        ]

        if window_slice != containing_window.lines:
            return CommandResponse(
                output="File changed since view was generated. Refresh views.",
                processed=False,
            )

        # Perform edit
        new_lines = (
            current_lines[: start_line - 1] + new_content + current_lines[end_line:]
        )
        try:
            filepath.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
        except (OSError, IOError) as e:
            return CommandResponse(output=f"Write failed: {e}", processed=False)

        return CommandResponse(
            output=f"Edited {filepath.relative_to(self._project_dir)} lines {start_line}-{end_line}",
            processed=True,
        )

    @command(
        signature="close label <name> | close pattern <glob> | close all",
        examples=[
            ("Close a specific query by label", "close label my_view"),
            ("Close queries matching a pattern", "close pattern hypothesis_1_*"),
            ("Close all active queries", "close all"),
        ],
    )
    def _handle_close(self, cmd: str) -> CommandResponse:
        """Remove one or more active queries to free screen space and line budget.

        Three variants:
          close label <name>    — remove the query with this exact label
          close pattern <glob>  — remove all queries whose label matches the glob
          close all             — remove every active query

        Closing queries frees their line budget (counted toward the 3000-line
        total cap), making room for new or larger views.
        """
        import fnmatch

        cmd = cmd.strip()

        # Parse close command variants
        if cmd == "close all":
            count = len(self._active_queries)
            self._active_queries.clear()
            return CommandResponse(output=f"Closed all {count} queries", processed=True)
        elif cmd.startswith("close label "):
            label = cmd[12:].strip()
            if label in self._active_queries:
                del self._active_queries[label]
                return CommandResponse(output=f"Closed query '{label}'", processed=True)
            return CommandResponse(output=f"No query '{label}'", processed=False)
        elif cmd.startswith("close pattern "):
            pattern = cmd[14:].strip()
            # Strip quotes if present
            if (pattern.startswith('"') and pattern.endswith('"')) or (
                pattern.startswith("'") and pattern.endswith("'")
            ):
                pattern = pattern[1:-1]

            to_remove = [
                label
                for label in self._active_queries.keys()
                if fnmatch.fnmatch(label, pattern)
            ]

            if not to_remove:
                return CommandResponse(
                    output=f"No queries match pattern '{pattern}'", processed=False
                )

            for label in to_remove:
                del self._active_queries[label]

            return CommandResponse(
                output=f"Closed {len(to_remove)} queries matching '{pattern}'",
                processed=True,
            )
        else:
            return CommandResponse(
                output="Invalid close syntax. Use: close label <name>, close pattern <glob>, or close all",
                processed=False,
            )

    @command(
        signature="create <file>",
        examples=[
            ("Create a new Python file", "create src/new.py\nprint('hello')\n"),
        ],
    )
    def _handle_create(self, cmd_lines: list[str]) -> CommandResponse:
        """Create a new file with initial content.

        Parameters:
          file    — path relative to the project directory (first line of command)
          content — file content, written on the lines following the create
                    command (multiline command); omit for an empty file

        The file must not already exist. Parent directories are created
        automatically. The path must be within the project directory.
        """
        if not cmd_lines:
            return CommandResponse(output="No create command provided", processed=False)

        # Parse: first line is "create <filepath>", rest is content
        first_line = cmd_lines[0].strip()
        if not first_line.startswith("create "):
            return CommandResponse(
                output="Invalid create syntax. Expected: create <file>", processed=False
            )

        filepath_str = first_line[7:].strip()  # Remove "create "
        filepath = self._project_dir / filepath_str

        # Validate filepath
        is_valid, error_msg = self._validate_filepath(filepath_str)
        if not is_valid:
            return CommandResponse(output=error_msg, processed=False)

        # Check if file exists
        if filepath.exists():
            return CommandResponse(
                output=f"File already exists: {filepath_str}", processed=False
            )

        # Get content (everything after first line)
        new_content = cmd_lines[1:] if len(cmd_lines) > 1 else []

        # Create parent directory if needed
        filepath.parent.mkdir(parents=True, exist_ok=True)

        # Write file
        try:
            filepath.write_text("\n".join(new_content) + "\n", encoding="utf-8")
        except (OSError, IOError) as e:
            return CommandResponse(output=f"Create failed: {e}", processed=False)

        return CommandResponse(
            output=f"Created {filepath_str} ({len(new_content)} lines)", processed=True
        )

    def get_state_display(self) -> str:
        """Generate screen by re-executing all queries."""
        all_windows = []
        queries_to_remove = []

        # Re-execute all active queries
        for label, query in self._active_queries.items():
            try:
                windows = self._executor.execute(query.ast, query.excluded_files)

                if not windows:
                    queries_to_remove.append(label)
                else:
                    all_windows.extend(windows)
            except Exception:
                # Query execution failed - remove it
                queries_to_remove.append(label)

        # Auto-remove exhausted/failed queries
        for label in queries_to_remove:
            del self._active_queries[label]

        # Merge and deduplicate
        views = self._window_manager.merge_overlapping(all_windows)

        # Cache merged views for edit verification.
        # Merged views span the full visible range, so edits spanning multiple
        # query windows (e.g. from a /^/ pattern that creates one window per line)
        # are correctly allowed when all lines are visible on screen.
        self._cached_windows = views

        # Build label → creation-time map for file ordering (most recent last)
        label_order = {
            label: query.created_at for label, query in self._active_queries.items()
        }

        # Format for screen
        return self._window_manager.format_for_screen(
            views, total_queries=len(self._active_queries), label_order=label_order
        )

    def generate_tag_summary(self) -> str:
        """Called on </editor> tag close to generate AI summary."""
        if not self._tag_windows:
            return ""

        summary, metadata = self._summarizer.generate_summary(
            self._tag_windows, self._tag_patterns
        )

        # Clear tag state
        self._tag_windows = []
        self._tag_patterns = []

        return f"\nSummary: {summary}"

    def _execute_command(self, method, cmd_text: str) -> str:
        """Override to handle multi-line commands."""
        cmd_lines = cmd_text.split("\n")
        first_line = cmd_lines[0].strip()

        # Multi-line commands (edit and create)
        if first_line.startswith("edit ") or first_line.startswith("create "):
            response = method(cmd_lines)
        else:
            # Single-line commands: pass first line
            response = method(first_line)

        # Convert CommandResponse to string
        if isinstance(response, CommandResponse):
            if not response.processed:
                raise ValueError(response.output)
            return response.output

        return response

    # Helper methods
    def _calculate_existing_lines(self) -> int:
        """Calculate total lines from existing queries."""
        total = 0
        for query in self._active_queries.values():
            try:
                windows = self._executor.execute(query.ast, query.excluded_files)
                total += sum(w.line_count for w in windows)
            except Exception:
                pass
        return total

    def _format_view_response(
        self, windows: list[Window], label: str, total_lines: int
    ) -> str:
        """Format view command response."""
        if not windows:
            return f"Query '{label}' matched no results"

        files = len(set(w.filepath for w in windows))
        existing = len(self._active_queries)

        return (
            f"Created query '{label}' with {len(windows)} windows across {files} file(s)\n"
            f"Total: {total_lines} lines ({existing} queries active, {self._calculate_existing_lines()}/{MAX_TOTAL_LINES} lines used)"
        )

    def _format_read_only_peek_response(self, windows: list[Window]) -> str:
        """Format read-only-peek command response."""
        if not windows:
            return "No matches found"

        lines = []
        total_lines = sum(w.line_count for w in windows)
        lines.append(
            f"Found {len(windows)} windows ({total_lines}/{READ_ONLY_PEEK_HARD_LIMIT} lines):\n"
        )

        for w in windows:
            lines.append(
                f"{w.filepath.relative_to(self._project_dir)} lines {w.start_line}-{w.end_line}:"
            )
            for i, line in enumerate(w.lines):
                display_line = line[:200] if len(line) > 200 else line
                lines.append(f"{display_line}")
            lines.append("")

        return "\n".join(lines)

    def _parse_edit(self, cmd_lines: list[str]) -> Optional[dict]:
        """Parse edit command."""
        if not cmd_lines:
            return None

        match = re.match(r"edit\s+(\S+)\s+(\d+)-(\d+)$", cmd_lines[0].strip())
        if not match:
            return None

        filepath_str = match.group(1)
        start_line = int(match.group(2))
        end_line = int(match.group(3))
        new_content = cmd_lines[1:] if len(cmd_lines) > 1 else []

        return {
            "filepath": filepath_str,
            "start_line": start_line,
            "end_line": end_line,
            "new_content": new_content,
        }

    def _validate_filepath(self, filepath_str: str) -> tuple[bool, str]:
        """Validate filepath is within project directory."""
        try:
            filepath = (self._project_dir / filepath_str).resolve()
            project_dir_resolved = self._project_dir.resolve()

            if not filepath.is_relative_to(project_dir_resolved):
                return (
                    False,
                    f"Path outside project directory: {filepath_str}",
                )
            return (True, "")
        except (ValueError, OSError) as e:
            return (False, f"Invalid path: {filepath_str} ({e})")

    def _read_file_lines(self, filepath: Path) -> list[str]:
        """Read all lines from file."""
        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                return [line.rstrip("\n") for line in f.readlines()]
        except (OSError, IOError):
            return []

    @command(
        signature="sed <label> /pattern/replacement/[flags]",
        examples=[
            (
                "Replace TODO with DONE in visible lines",
                "sed todos /TODO/DONE/g",
            ),
            (
                "Rename a module across multiple files",
                "sed imports /from old_module/from new_module/g",
            ),
            (
                "Use capture groups to refactor function calls",
                "sed calls /process_data\((\w+),\s*(\w+)\)/process_data(input=$1, output=$2)/g",
            ),
        ],
    )
    def _handle_sed(self, cmd: str) -> CommandResponse:
        """Perform search-and-replace on content visible in a named view.

        Parameters:
          label       — name of a view whose visible lines will be modified
          pattern     — regex pattern to search for
          replacement — replacement text (supports $1, $2, etc. for capture groups)
          flags       — optional: g (global - replace all occurrences per line),
                        i (case-insensitive)

        Only lines currently visible in the named view are modified. This ensures
        safety - you can only change what you can see. Other occurrences of the
        pattern in the same file but outside the view are unchanged.

        Returns a summary showing:
          - Number of replacements made
          - Files modified and which lines were changed

        Examples:
          sed todos /TODO/DONE/g           — replace all TODO with DONE
          sed imports /old/new/g           — rename across multiple files
          sed calls /foo\((\w+)\)/bar($1)/g — use capture groups
        """
        # Parse sed command: sed <label> /pattern/replacement/[flags]
        parsed = self._parse_sed(cmd)
        if not parsed:
            return CommandResponse(
                output="Invalid sed syntax. Expected: sed <label> /pattern/replacement/[flags]",
                processed=False,
            )

        label = parsed["label"]
        pattern = parsed["pattern"]
        replacement = parsed["replacement"]
        flags = parsed["flags"]

        # Find windows for the given label
        label_windows = self._find_windows_for_label(label)
        if label_windows is None:
            active_labels = list(self._active_queries.keys())
            return CommandResponse(
                output=f"No view found with label '{label}'\n"
                f"Active views: {', '.join(active_labels) if active_labels else 'none'}",
                processed=False,
            )

        if not label_windows:
            return CommandResponse(
                output=f"View '{label}' has no visible lines to operate on",
                processed=False,
            )

        # Validate regex pattern
        try:
            regex_flags = re.IGNORECASE if "i" in flags else 0
            compiled_pattern = re.compile(pattern, regex_flags)
        except re.error as e:
            return CommandResponse(
                output=f"Invalid regex pattern: {pattern}\nDetails: {e}",
                processed=False,
            )

        # Convert $1, $2, etc. to \1, \2, etc. for Python regex
        py_replacement = self._convert_replacement(replacement)

        # Group windows by file
        windows_by_file: dict[Path, list[Window | View]] = {}
        for window in label_windows:
            filepath = window.filepath
            if filepath not in windows_by_file:
                windows_by_file[filepath] = []
            windows_by_file[filepath].append(window)

        # Process each file
        changes_by_file: dict[Path, list[int]] = (
            {}
        )  # filepath -> list of line numbers changed
        total_replacements = 0

        for filepath, windows in windows_by_file.items():
            # Read current file content
            current_lines = self._read_file_lines(filepath)
            if not current_lines:
                continue

            # Collect visible line ranges for this file
            visible_ranges = []
            for window in windows:
                visible_ranges.append((window.start_line, window.end_line))

            # Merge overlapping ranges
            visible_ranges.sort()
            merged_ranges = []
            for start, end in visible_ranges:
                if merged_ranges and start <= merged_ranges[-1][1] + 1:
                    merged_ranges[-1] = (
                        merged_ranges[-1][0],
                        max(merged_ranges[-1][1], end),
                    )
                else:
                    merged_ranges.append((start, end))

            # Apply substitutions only to visible lines
            new_lines = current_lines.copy()
            file_changes = []

            global_replace = "g" in flags

            for start, end in merged_ranges:
                for line_num in range(start, end + 1):
                    idx = line_num - 1  # Convert to 0-based
                    if idx < 0 or idx >= len(new_lines):
                        continue

                    original_line = new_lines[idx]

                    # Count replacements
                    if global_replace:
                        new_line, count = compiled_pattern.subn(
                            py_replacement, original_line
                        )
                    else:
                        # Replace only first occurrence
                        new_line, count = compiled_pattern.subn(
                            py_replacement, original_line, count=1
                        )

                    if count > 0:
                        new_lines[idx] = new_line
                        file_changes.append(line_num)
                        total_replacements += count

            if file_changes:
                changes_by_file[filepath] = sorted(set(file_changes))

                # Write modified file
                try:
                    filepath.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
                except (OSError, IOError) as e:
                    return CommandResponse(
                        output=f"Write failed for {filepath}: {e}",
                        processed=False,
                    )

        # Format response
        if total_replacements == 0:
            return CommandResponse(
                output="No occurrences of pattern found in visible lines",
                processed=True,
            )

        # Build summary
        response_lines = [
            f"Replaced {total_replacements} occurrence(s) in {len(changes_by_file)} file(s)"
        ]

        for filepath in sorted(changes_by_file.keys()):
            lines = changes_by_file[filepath]
            rel_path = filepath.relative_to(self._project_dir)
            if len(lines) <= 10:
                response_lines.append(f"  {rel_path}: {', '.join(map(str, lines))}")
            else:
                response_lines.append(
                    f"  {rel_path}: {', '.join(map(str, lines[:10]))}... ({len(lines)} lines)"
                )

        return CommandResponse(
            output="\n".join(response_lines),
            processed=True,
        )

    def _parse_sed(self, cmd: str) -> Optional[dict]:
        """Parse sed command.

        Format: sed <label> /pattern/replacement/[flags]

        Returns dict with label, pattern, replacement, flags or None if invalid.
        """
        cmd = cmd.strip()
        if not cmd.startswith("sed "):
            return None

        rest = cmd[4:].strip()  # Remove "sed "

        # Find label (first word)
        parts = rest.split(None, 1)
        if len(parts) < 2:
            return None

        label = parts[0]
        pattern_part = parts[1]

        # Parse /pattern/replacement/[flags]
        if not pattern_part.startswith("/"):
            return None

        # Find the delimiter positions
        # Format: /pattern/replacement/[flags]
        # Pattern and replacement can contain escaped slashes (\/)
        delimiter = "/"

        # Parse pattern (between first and second unescaped /)
        pattern_start = 1  # after first /
        pattern_end = self._find_unescaped(pattern_part, delimiter, pattern_start)
        if pattern_end is None:
            return None

        pattern = pattern_part[pattern_start:pattern_end]
        # Unescape \/ in pattern
        pattern = pattern.replace("\\/", "/")

        # Parse replacement (between second and third unescaped /)
        replacement_start = pattern_end + 1
        replacement_end = self._find_unescaped(
            pattern_part, delimiter, replacement_start
        )
        if replacement_end is None:
            # Allow replacement without trailing /
            replacement = pattern_part[replacement_start:]
            flags = ""
        else:
            replacement = pattern_part[replacement_start:replacement_end]
            # Unescape \/ in replacement
            replacement = replacement.replace("\\/", "/")
            flags = pattern_part[replacement_end + 1 :].strip()

        return {
            "label": label,
            "pattern": pattern,
            "replacement": replacement,
            "flags": flags,
        }

    def _find_unescaped(self, text: str, char: str, start: int) -> Optional[int]:
        """Find the first unescaped occurrence of char in text starting from start.

        An escaped character (preceded by \) is not considered a match.
        """
        i = start
        while i < len(text):
            if text[i] == char and (i == 0 or text[i - 1] != "\\"):
                return i
            i += 1
        return None

    def _convert_replacement(self, replacement: str) -> str:
        """Convert sed-style replacement ($1, $2, etc.) to Python regex style (\\1, \\2, etc.)."""
        # Replace $1, $2, ..., $9 with \1, \2, ..., \9
        result = replacement
        for i in range(1, 10):
            result = result.replace(f"${i}", f"\\{i}")
        return result

    def _find_windows_for_label(self, label: str) -> Optional[list[Window | View]]:
        """Find all windows/views for a given label.

        Returns:
            List of windows/views, or None if label doesn't exist.
            Empty list if label exists but has no visible lines.
        """
        # Check if label exists in active queries
        if label not in self._active_queries:
            return None

        # Get cached windows (merged views)
        windows = []

        # The _cached_windows contains merged View objects after get_state_display
        for window in self._cached_windows:
            # Check if this window's labels include the target label
            if hasattr(window, "labels"):
                # It's a View
                if label in window.labels:
                    windows.append(window)
            else:
                # It's a Window
                if window.label == label:
                    windows.append(window)

        return windows
