"""Window and view management for editor environment.

This module handles window merging, deduplication, and screen formatting.
Windows are generated by query execution, then merged and formatted for display.
"""

from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Window:
    """A contiguous range of lines from a single file.

    Windows are the result of executing a query. They may overlap or duplicate
    with other windows from different queries.
    """

    filepath: Path
    start_line: int  # 1-based
    end_line: int  # 1-based, inclusive
    lines: list[str]  # Actual content
    label: str  # Query label that generated this window

    @property
    def line_count(self) -> int:
        """Return number of lines in this window."""
        return self.end_line - self.start_line + 1


@dataclass
class View:
    """A view on screen after merging and deduplication.

    Views are created from windows after overlapping windows are merged.
    """

    filepath: Path
    start_line: int  # 1-based
    end_line: int  # 1-based, inclusive
    lines: list[str]  # Actual content
    labels: list[str]  # All query labels contributing to this view

    @property
    def line_count(self) -> int:
        """Return number of lines in this view."""
        return self.end_line - self.start_line + 1


class WindowManager:
    """Manages window merging, deduplication, and screen formatting."""

    def merge_overlapping(self, windows: list[Window]) -> list[View]:
        """Merge overlapping or adjacent windows within same file.

        Algorithm:
        1. Group windows by file
        2. Sort by start_line
        3. Merge overlapping/adjacent windows (within 1 line)
        4. Track labels from all contributing windows

        Args:
            windows: List of windows from query execution

        Returns:
            List of views after merging

        Examples:
            >>> mgr = WindowManager()
            >>> w1 = Window(Path("a.py"), 1, 5, ["line1", "line2", "line3", "line4", "line5"], "q1")
            >>> w2 = Window(Path("a.py"), 4, 8, ["line4", "line5", "line6", "line7", "line8"], "q2")
            >>> views = mgr.merge_overlapping([w1, w2])
            >>> len(views)
            1
            >>> views[0].start_line, views[0].end_line
            (1, 8)
            >>> views[0].labels
            ['q1', 'q2']
        """
        if not windows:
            return []

        # Group by file
        by_file = defaultdict(list)
        for w in windows:
            by_file[w.filepath].append(w)

        views = []
        for filepath, file_windows in sorted(by_file.items(), key=lambda x: str(x[0])):
            # Sort by start_line
            sorted_windows = sorted(file_windows, key=lambda w: w.start_line)

            # Merge overlapping/adjacent windows
            merged = self._merge_windows_for_file(sorted_windows)
            views.extend(merged)

        return views

    def _merge_windows_for_file(self, windows: list[Window]) -> list[View]:
        """Merge windows for a single file.

        Args:
            windows: Sorted list of windows from same file

        Returns:
            List of views after merging
        """
        if not windows:
            return []

        views = []
        current_start = windows[0].start_line
        current_end = windows[0].end_line
        current_labels = [windows[0].label]
        filepath = windows[0].filepath

        for next_window in windows[1:]:
            # Check if overlapping or adjacent (within 1 line gap)
            if next_window.start_line <= current_end + 1:
                # Merge: extend current window
                current_end = max(current_end, next_window.end_line)
                if next_window.label not in current_labels:
                    current_labels.append(next_window.label)
            else:
                # Gap: finalize current view, start new one
                lines = self._read_lines(filepath, current_start, current_end)
                views.append(
                    View(
                        filepath=filepath,
                        start_line=current_start,
                        end_line=current_end,
                        lines=lines,
                        labels=current_labels,
                    )
                )
                current_start = next_window.start_line
                current_end = next_window.end_line
                current_labels = [next_window.label]

        # Add final view
        lines = self._read_lines(filepath, current_start, current_end)
        views.append(
            View(
                filepath=filepath,
                start_line=current_start,
                end_line=current_end,
                lines=lines,
                labels=current_labels,
            )
        )

        return views

    def _read_lines(self, filepath: Path, start_line: int, end_line: int) -> list[str]:
        """Read lines from file.

        Args:
            filepath: Path to file
            start_line: Start line (1-based)
            end_line: End line (1-based, inclusive)

        Returns:
            List of lines (without newlines)
        """
        try:
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                all_lines = f.readlines()

            # Extract range (convert to 0-based indexing)
            lines = all_lines[start_line - 1 : end_line]

            # Remove trailing newlines
            return [line.rstrip("\n") for line in lines]
        except (OSError, IOError):
            # File doesn't exist or can't be read
            return [f"[Error reading {filepath}]"]

    def format_for_screen(self, views: list[View], total_queries: int = 0) -> str:
        """Format views for screen display.

        Args:
            views: List of views to display
            total_queries: Total number of active queries

        Returns:
            Formatted string for screen display

        Examples:
            >>> mgr = WindowManager()
            >>> v = View(Path("test.py"), 10, 12, ["def foo():", "    return 42", ""], ["q1"])
            >>> output = mgr.format_for_screen([v], 1)
            >>> "test.py" in output
            True
            >>> "10-12" in output
            True
        """
        if not views:
            total_lines = 0
            header = f"Views ({total_queries} queries, {total_lines}/3000 lines):"
            return header + "\n  (no matches)"

        # Calculate total lines
        total_lines = sum(v.line_count for v in views)

        # Header
        header = f"Views ({total_queries} queries, {total_lines}/3000 lines):"
        lines = [header, ""]

        # Group by file
        by_file = defaultdict(list)
        for v in views:
            by_file[v.filepath].append(v)

        # Format each file's views
        for filepath in sorted(by_file.keys(), key=str):
            file_views = sorted(by_file[filepath], key=lambda v: v.start_line)
            file_total_lines = sum(v.line_count for v in file_views)

            # File header
            lines.append(
                f"{filepath} ({len(file_views)} views, {file_total_lines} lines):"
            )

            # Each view
            for view in file_views:
                # View header with labels
                labels_str = ", ".join(view.labels)
                lines.append(
                    f"  [{labels_str}] lines {view.start_line}-{view.end_line} ({view.line_count} lines)"
                )

                # View content (indented)
                for i, line in enumerate(view.lines):
                    line_num = view.start_line + i
                    # Truncate very long lines
                    display_line = line[:200] if len(line) > 200 else line
                    lines.append(f"   {line_num:4d}  {display_line}")

                lines.append("")  # Blank line after each view

            lines.append("")  # Blank line after each file

        return "\n".join(lines).rstrip()

    def calculate_total_lines(self, views: list[View]) -> int:
        """Calculate total lines across all views.

        Args:
            views: List of views

        Returns:
            Total number of lines
        """
        return sum(v.line_count for v in views)
